### PR TITLE
Hindi translation

### PR DESCRIPTION
**Pull request by jaideepghosh**
This PR includes:
• Latest key changes.
• Added missing transalations.

### CODE REVIEW

**Comment by jaideepghosh** [comment]
Hi @SachaG ,
Please have a look on the translations.
And merge the changes :)

**Comment by jaideepghosh** [comment]
Hey @SachaG 
Any update on this PR?

**Comment by SachaG** [comment]
First of all, thanks again for your help with translating the 2019 edition of the survey. Also, we've started our translation efforts for this year, and this time we'll try to translate the survey questions as well! 

More info here: https://github.com/StateOfJS/StateOfCSS-2020/issues/2

**Comment by SachaG** [comment]
Oh also I'll look at this PR now, sorry for the delay!

**Pull request merged**
