### PR TITLE
Hindi translation  🇮🇳

### PR DESCRIPTION
**Pull request by jaideepghosh**
### User Interface

- [X] Tshirt

#### Demographics

- [X] Salary Ranges
- [X] Years of Experience
- [X] Company Size
- [X] Sources
- [X] CSS Proficiency
- [X] Back-end Proficiency
- [X] Job Title
- [X] Gender
- [X] Other

#### Features

- [X] General
- [X] Feature Overview
- [X] Features Section Overview

#### Tools

- [X] General
- [X] Rankings
- [X] Overview
- [X] Arrows
- [X] Quadrants
- [X] Happiness
- [X] Experience
- [X] Other Tools

#### Other Tools

- [X] Other Tools
- [X] Resources
- [X] Opinions
- [X] Awards

#### Generic

- [X] Pages
- [X] Sharing
- [X] Export
- [X] General
- [X] Partners
- [X] Charts
- [X] Other

### Introductions

- [X] Introduction
- [X] Demographics
- [X] Features
- [X] Flavors
- [X] Front-end Frameworks
- [X] Data Layer
- [X] Testing
- [X] Back-end Frameworks
- [X] Mobile & Desktop
- [X] Other Tools
- [X] Resources
- [X] Opinions
- [X] Awards

### Conclusions

- [X] Conclusion

### CODE REVIEW

**Comment by jaideepghosh** [comment]
Hi @SachaG ,
Please have a look on the translations. And merge the changes :)

**Comment by SachaG** [comment]
Sorry it took me a while! Thanks so much for your work :)

**Comment by SachaG** [comment]
@jaideepghosh I know it's been a while, but would you be able to help us translate this year's survey questions for the State of CSS survey by any chance?

https://github.com/StateOfJS/StateOfCSS-2020/issues/2

**Comment by jaideepghosh** [comment]
> @jaideepghosh I know it's been a while, but would you be able to help us translate this year's survey questions for the State of CSS survey by any chance?
> 
> [StateOfJS/StateOfCSS-2020#2](https://github.com/StateOfJS/StateOfCSS-2020/issues/2)

Hey @SachaG 
I'll translate this year's survey questions for the State of CSS survey. Will raise a PR soon with the `WIP` title, and once it is done, I'll tag you in the next comment in that PR.

**Comment by SachaG** [comment]
Awesome, thanks!

**Comment by jaideepghosh** [comment]
Hey @SachaG 
I've pushed the translations for state-of-css in PR id [47](https://github.com/StateOfJS/StateOfJS-Vulcan/pull/47)

**Pull request merged**
