### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by impodracer**
#### User Interface

- [x] Tshirt

#### Demographics

- [x] Salary Ranges
- [x] Years of Experience
- [x] Company Size
- [x] Sources
- [x] CSS Proficiency
- [x] Back-end Proficiency
- [x] Job Title
- [x] Gender
- [x] Other

#### Features

- [x] General
- [x] Feature Overview
- [x] Features Section Overview

#### Tools

- [x] General
- [x] Rankings
- [x] Overview
- [x] Arrows
- [x] Quadrants
- [x] Happiness
- [x] Experience
- [x] Other Tools

#### Other Tools

- [x] Other Tools
- [x] Resources
- [x] Opinions
- [x] Awards

#### Generic

- [x] Pages
- [x] Sharing
- [x] Export
- [x] General
- [x] Partners
- [x] Charts
- [x] Other

### Introductions

- [x] Introduction
- [x] T-shirt
- [x] Demographics
- [x] Overview
- [x] Features
- [x] Flavors
- [x] Front-end Frameworks
- [x] Data Layer
- [x] Testing
- [x] Back-end Frameworks
- [x] Mobile & Desktop
- [x] Other Tools
- [x] Resources
- [x] Opinions
- [x] Awards
- [x] Support

### Conclusions

- [x] Conclusion

### CODE REVIEW

**Comment by zenyr** [comment]
Hello, I've been working on Korean but stalled at #47. Can you add me to your repo as a collaborator?

**Comment by impodracer** [comment]
@zenyr Sure! I invited you as a collaborator :)

**Comment by zenyr** [comment]
FYI https://github.com/impodracer/State-of-JS-2019/pulls will show my translations ready to be merged. Maybe we could review them as a whole once we finish the first pass, then merge into the upstream here.

**Comment by impodracer** [comment]
Well, There is nothing I can say about this great works :) So I merged all PRs.

**Comment by zenyr** [comment]
🚀

**Comment by SachaG** [comment]
Thanks so much, this is great!

**Comment by SachaG** [comment]
First of all, thanks again for your help with translating the 2019 edition of the survey. Also, we've started our translation efforts for this year, and this time we'll try to translate the survey questions as well! 

More info here: https://github.com/StateOfJS/StateOfCSS-2020/issues/2

**Pull request merged**
