### PR TITLE
Tシャツに関する部分を翻訳

### PR DESCRIPTION
**Pull request by tnzk**
（これはプルリク作成の参考用です）

* Tシャツの仕様部分を翻訳

### CODE REVIEW

**Comment by tnzk** [comment]
I've created this PR mistakenly. Please ignore this.

**Comment by SachaG** [comment]
@tnzk I know it's been a while, but would you be able to help us translate this year's survey questions for the State of CSS survey by any chance?

https://github.com/StateOfJS/StateOfCSS-2020/issues/2

**Comment by tnzk** [comment]
@SachaG I'd like to help! I will join the issue later. It's been a year btw. wow...

**Comment by thetkay** [comment]
@SachaG @tnzk 
I guess @tnzk already works on this translation.
But there is a room which I can join to translate, I wanna be in.

If I can, please let me know :')
Thanks.

**Pull request closed without merging**
