### PR TITLE
German translation 🇩🇪 WIP

### PR DESCRIPTION
**Pull request by smetzdev**
- [ ] conclusions/conclusion
- [ ] introductions/awards
- [ ] introductions/demographics
- [ ] introductions/iintroduction (lkreimann)
- [ ] introductions/opinions
- [ ] introductions/other-tools
- [ ] introductions/overview
- [ ] introductions/resources
- [ ] introductions/support
- [ ] introductions/t-shirt
- [ ] introductions/features/browser_apis
- [ ] introductions/features/data_structures
- [ ] introductions/features/features
- [ ] introductions/features/language
- [ ] introductions/features/other_features
- [ ] introductions/features/syntax
- [ ] introductions/tools/back_end_frameworks
- [ ] introductions/tools/data_layer
- [ ] introductions/tools/front_end_frameworks
- [ ] introductions/tools/javascript_flavors
- [ ] introductions/tool/mobile_desktop
- [ ] introductions/tools/testing
- [ ] de-DE.yml (r3sMetz)

### CODE REVIEW

**Comment by lkreimann** [comment]
Happy to help :)

**Comment by r3sMetz** [comment]
Sure, thanks! Ill edit a checklist tomorow and then we can get started!

**Comment by lkreimann** [comment]
Awesome! :blush:

**Comment by r3sMetz** [comment]
Hey, ive added the checklist to the top of the issue and also assigned you as a collaborator. You can pick one (ore multiple) topics, so nobody works on the same file 🤓

**Comment by lkreimann** [comment]
Gonna start contributing tomorrow :) Thanks for the invite and the checklist :blush: that helps a lot!

**Comment by r3sMetz** [comment]
Nice! Please let me know which file you're starting with then.

**Comment by lkreimann** [comment]
Gonna start with `introductions/introduction`

**Comment by r3sMetz** [comment]
Perfect, iam gonna start with the de-DE.yml file, could take a while.

**Comment by r3sMetz** [comment]
Do you prefer working in seperate branches per file, or should we just be rebels and push to master? ^^

**Comment by lkreimann** [comment]
I think I can live with both, but I guess branches would be a little less chaotic tbh. But I'm totally with you making that decision :)

**Comment by r3sMetz** [comment]
Well as long as were only working on separate files at a time, i think we should just go 🤠- mode

**Comment by SachaG** [comment]
First of all, thanks again for your help with translating the 2019 edition of the survey. Also, we've started our translation efforts for this year, and this time we'll try to translate the survey questions as well! 

More info here: https://github.com/StateOfJS/StateOfCSS-2020/issues/2

**Pull request closed without merging**
